version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://your_username:your_password@db:5432/your_database
      REDIS_URL: redis://redis:6379
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    ports:
      - "5432:5432"
  redis:
    image: redis
